const mongoose = require('mongoose');
const Icon = require('./models/Icon');
require('dotenv').config();

const RESOURCE_ICONS = {
  gold: '/icons/resources/gold.svg',
  copper: '/icons/resources/copper.svg',
  iron: '/icons/resources/iron.svg',
  rare_metals: '/icons/resources/rare_metals.svg',
  oil_gas: '/icons/resources/oil_gas.svg',
  diamonds: '/icons/resources/diamonds.svg',
  coal: '/icons/resources/coal.svg',
};

const MINING_SITES = [
  // ===== GOLD (20) =====
  { name: 'Muruntau', continent: 'asia', country: 'UZ', lat: 41.52, lng: 64.57, resourceType: 'gold', hashrate: 700, price: 185, valuationUsd: '$5.5B', rarity: 'epic', resourceEmoji: '🟡', description: 'Крупнейший золотой карьер, Узбекистан', descriptionEn: 'Largest open-pit gold mine, Uzbekistan', order: 1 },
  { name: 'Carlin Trend', continent: 'north_america', country: 'US', lat: 40.72, lng: -116.07, resourceType: 'gold', hashrate: 650, price: 170, valuationUsd: '$4.8B', rarity: 'epic', resourceEmoji: '🟡', description: 'Золотоносный район Невады, США', descriptionEn: 'Gold district in Nevada, USA', order: 2 },
  { name: 'Grasberg', continent: 'asia', country: 'ID', lat: -4.05, lng: 137.11, resourceType: 'gold', hashrate: 750, price: 200, valuationUsd: '$6B', rarity: 'legendary', resourceEmoji: '🟡', description: 'Крупнейшее золото-медное месторождение, Индонезия', descriptionEn: 'Largest gold-copper deposit, Indonesia', order: 3 },
  { name: 'Olimpiada', continent: 'russia', country: 'RU', lat: 58.73, lng: 93.65, resourceType: 'gold', hashrate: 600, price: 155, valuationUsd: '$4.2B', rarity: 'epic', resourceEmoji: '🟡', description: 'Крупнейший золотой рудник России', descriptionEn: 'Largest gold mine in Russia', order: 4 },
  { name: 'Cortez', continent: 'north_america', country: 'US', lat: 40.15, lng: -116.6, resourceType: 'gold', hashrate: 550, price: 145, valuationUsd: '$3.8B', rarity: 'rare', resourceEmoji: '🟡', description: 'Золотой рудник в Неваде, США', descriptionEn: 'Gold mine in Nevada, USA', order: 5 },
  { name: 'Pueblo Viejo', continent: 'north_america', country: 'DO', lat: 18.95, lng: -70.18, resourceType: 'gold', hashrate: 580, price: 150, valuationUsd: '$4B', rarity: 'rare', resourceEmoji: '🟡', description: 'Золотой рудник, Доминикана', descriptionEn: 'Gold mine, Dominican Republic', order: 6 },
  { name: 'Lihir', continent: 'australia', country: 'PG', lat: -3.12, lng: 152.64, resourceType: 'gold', hashrate: 560, price: 148, valuationUsd: '$3.9B', rarity: 'rare', resourceEmoji: '🟡', description: 'Золотой рудник, Папуа-Новая Гвинея', descriptionEn: 'Gold mine, Papua New Guinea', order: 7 },
  { name: 'Kibali', continent: 'africa', country: 'CD', lat: 3.01, lng: 29.59, resourceType: 'gold', hashrate: 520, price: 140, valuationUsd: '$3.5B', rarity: 'rare', resourceEmoji: '🟡', description: 'Крупнейший золотой рудник Африки, ДР Конго', descriptionEn: 'Largest gold mine in Africa, DR Congo', order: 8 },
  { name: 'Boddington', continent: 'australia', country: 'AU', lat: -32.75, lng: 116.38, resourceType: 'gold', hashrate: 540, price: 142, valuationUsd: '$3.6B', rarity: 'rare', resourceEmoji: '🟡', description: 'Крупнейший золотой рудник Австралии', descriptionEn: 'Largest gold mine in Australia', order: 9 },
  { name: 'Loulo-Gounkoto', continent: 'africa', country: 'ML', lat: 14.43, lng: -11.67, resourceType: 'gold', hashrate: 480, price: 130, valuationUsd: '$3.2B', rarity: 'rare', resourceEmoji: '🟡', description: 'Золотой комплекс, Мали', descriptionEn: 'Gold complex, Mali', order: 10 },
  { name: 'Cadia Valley', continent: 'australia', country: 'AU', lat: -33.47, lng: 148.99, resourceType: 'gold', hashrate: 500, price: 135, valuationUsd: '$3.4B', rarity: 'rare', resourceEmoji: '🟡', description: 'Золото-медный рудник, Австралия', descriptionEn: 'Gold-copper mine, Australia', order: 11 },
  { name: 'South Deep', continent: 'africa', country: 'ZA', lat: -26.42, lng: 27.67, resourceType: 'gold', hashrate: 450, price: 120, valuationUsd: '$2.8B', rarity: 'rare', resourceEmoji: '🟡', description: 'Глубочайший золотой рудник, ЮАР', descriptionEn: 'Deepest gold mine, South Africa', order: 12 },
  { name: 'Mponeng', continent: 'africa', country: 'ZA', lat: -26.4, lng: 27.43, resourceType: 'gold', hashrate: 430, price: 115, valuationUsd: '$2.6B', rarity: 'rare', resourceEmoji: '🟡', description: 'Самый глубокий рудник в мире, ЮАР', descriptionEn: 'Deepest mine in the world, South Africa', order: 13 },
  { name: 'Canadian Malartic', continent: 'north_america', country: 'CA', lat: 48.13, lng: -78.12, resourceType: 'gold', hashrate: 470, price: 125, valuationUsd: '$3B', rarity: 'rare', resourceEmoji: '🟡', description: 'Крупнейший золотой карьер Канады', descriptionEn: 'Largest open-pit gold mine in Canada', order: 14 },
  { name: 'Norte Abierto', continent: 'south_america', country: 'CL', lat: -27.3, lng: -69.28, resourceType: 'gold', hashrate: 460, price: 122, valuationUsd: '$2.9B', rarity: 'rare', resourceEmoji: '🟡', description: 'Золото-медный проект, Чили', descriptionEn: 'Gold-copper project, Chile', order: 15 },
  { name: 'Obuasi', continent: 'africa', country: 'GH', lat: 6.2, lng: -1.68, resourceType: 'gold', hashrate: 400, price: 110, valuationUsd: '$2.4B', rarity: 'rare', resourceEmoji: '🟡', description: 'Исторический золотой рудник, Гана', descriptionEn: 'Historic gold mine, Ghana', order: 16 },
  { name: 'Detour Lake', continent: 'north_america', country: 'CA', lat: 50.05, lng: -79.72, resourceType: 'gold', hashrate: 440, price: 118, valuationUsd: '$2.7B', rarity: 'rare', resourceEmoji: '🟡', description: 'Золотой рудник, Канада', descriptionEn: 'Gold mine, Canada', order: 17 },
  { name: 'Yanacocha', continent: 'south_america', country: 'PE', lat: -6.97, lng: -78.53, resourceType: 'gold', hashrate: 420, price: 112, valuationUsd: '$2.5B', rarity: 'rare', resourceEmoji: '🟡', description: 'Крупнейший золотой рудник Южной Америки, Перу', descriptionEn: 'Largest gold mine in South America, Peru', order: 18 },
  { name: 'Pascua-Lama', continent: 'south_america', country: 'CL', lat: -29.32, lng: -70.08, resourceType: 'gold', hashrate: 380, price: 105, valuationUsd: '$2.2B', rarity: 'rare', resourceEmoji: '🟡', description: 'Трансграничный проект, Чили/Аргентина', descriptionEn: 'Cross-border project, Chile/Argentina', order: 19 },
  { name: 'Olympic Dam Gold', continent: 'australia', country: 'AU', lat: -30.45, lng: 136.88, resourceType: 'gold', hashrate: 500, price: 138, valuationUsd: '$3.5B', rarity: 'epic', resourceEmoji: '🟡', description: 'Полиметаллический гигант, Австралия', descriptionEn: 'Polymetallic giant, Australia', order: 20 },
  // ===== COPPER (20) =====
  { name: 'Escondida', continent: 'south_america', country: 'CL', lat: -24.27, lng: -69.07, resourceType: 'copper', hashrate: 780, price: 210, valuationUsd: '$7B', rarity: 'legendary', resourceEmoji: '🔴', description: 'Крупнейший медный рудник в мире, Чили', descriptionEn: 'Largest copper mine in the world, Chile', order: 21 },
  { name: 'Collahuasi', continent: 'south_america', country: 'CL', lat: -20.98, lng: -68.71, resourceType: 'copper', hashrate: 620, price: 165, valuationUsd: '$4.5B', rarity: 'epic', resourceEmoji: '🔴', description: 'Медный рудник на высоте 4400 м, Чили', descriptionEn: 'Copper mine at 4400m, Chile', order: 22 },
  { name: 'Kamoa-Kakula', continent: 'africa', country: 'CD', lat: -10.77, lng: 26.27, resourceType: 'copper', hashrate: 700, price: 190, valuationUsd: '$5.5B', rarity: 'epic', resourceEmoji: '🔴', description: 'Новейший медный гигант, ДР Конго', descriptionEn: 'Newest copper giant, DR Congo', order: 23 },
  { name: 'Grasberg Copper', continent: 'asia', country: 'ID', lat: -4.06, lng: 137.12, resourceType: 'copper', hashrate: 720, price: 195, valuationUsd: '$5.8B', rarity: 'legendary', resourceEmoji: '🔴', description: 'Крупнейший подземный медный рудник, Индонезия', descriptionEn: 'Largest underground copper mine, Indonesia', order: 24 },
  { name: 'Tenke Fungurume', continent: 'africa', country: 'CD', lat: -10.61, lng: 26.13, resourceType: 'copper', hashrate: 580, price: 155, valuationUsd: '$4B', rarity: 'epic', resourceEmoji: '🔴', description: 'Медно-кобальтовый рудник, ДР Конго', descriptionEn: 'Copper-cobalt mine, DR Congo', order: 25 },
  { name: 'El Teniente', continent: 'south_america', country: 'CL', lat: -34.09, lng: -70.35, resourceType: 'copper', hashrate: 600, price: 160, valuationUsd: '$4.3B', rarity: 'epic', resourceEmoji: '🔴', description: 'Крупнейший подземный медный рудник, Чили', descriptionEn: 'Largest underground copper mine, Chile', order: 26 },
  { name: 'Bingham Canyon', continent: 'north_america', country: 'US', lat: 40.52, lng: -112.15, resourceType: 'copper', hashrate: 560, price: 150, valuationUsd: '$3.8B', rarity: 'epic', resourceEmoji: '🔴', description: 'Крупнейший карьер в мире, США', descriptionEn: 'Largest open-pit mine, USA', order: 27 },
  { name: 'Cerro Verde', continent: 'south_america', country: 'PE', lat: -16.54, lng: -71.6, resourceType: 'copper', hashrate: 520, price: 140, valuationUsd: '$3.5B', rarity: 'rare', resourceEmoji: '🔴', description: 'Медный рудник, Перу', descriptionEn: 'Copper mine, Peru', order: 28 },
  { name: 'Antamina', continent: 'south_america', country: 'PE', lat: -9.53, lng: -77.06, resourceType: 'copper', hashrate: 510, price: 138, valuationUsd: '$3.4B', rarity: 'rare', resourceEmoji: '🔴', description: 'Медно-цинковый рудник, Перу', descriptionEn: 'Copper-zinc mine, Peru', order: 29 },
  { name: 'Chuquicamata', continent: 'south_america', country: 'CL', lat: -22.32, lng: -68.93, resourceType: 'copper', hashrate: 540, price: 145, valuationUsd: '$3.7B', rarity: 'epic', resourceEmoji: '🔴', description: 'Исторический медный карьер, Чили', descriptionEn: 'Historic copper mine, Chile', order: 30 },
  { name: 'Los Pelambres', continent: 'south_america', country: 'CL', lat: -31.72, lng: -70.49, resourceType: 'copper', hashrate: 490, price: 132, valuationUsd: '$3.2B', rarity: 'rare', resourceEmoji: '🔴', description: 'Медный рудник, Чили', descriptionEn: 'Copper mine, Chile', order: 31 },
  { name: 'Radomiro Tomic', continent: 'south_america', country: 'CL', lat: -22.27, lng: -68.9, resourceType: 'copper', hashrate: 480, price: 128, valuationUsd: '$3B', rarity: 'rare', resourceEmoji: '🔴', description: 'Медный карьер, Чили', descriptionEn: 'Copper open-pit, Chile', order: 32 },
  { name: 'Morenci', continent: 'north_america', country: 'US', lat: 33.08, lng: -109.33, resourceType: 'copper', hashrate: 500, price: 135, valuationUsd: '$3.3B', rarity: 'rare', resourceEmoji: '🔴', description: 'Крупнейший медный рудник США', descriptionEn: 'Largest copper mine in USA', order: 33 },
  { name: 'Mutanda', continent: 'africa', country: 'CD', lat: -10.68, lng: 25.95, resourceType: 'copper', hashrate: 460, price: 122, valuationUsd: '$2.8B', rarity: 'rare', resourceEmoji: '🔴', description: 'Медно-кобальтовый рудник, ДР Конго', descriptionEn: 'Copper-cobalt mine, DR Congo', order: 34 },
  { name: 'Kamoto', continent: 'africa', country: 'CD', lat: -10.73, lng: 25.43, resourceType: 'copper', hashrate: 440, price: 118, valuationUsd: '$2.6B', rarity: 'rare', resourceEmoji: '🔴', description: 'Медный рудник, ДР Конго', descriptionEn: 'Copper mine, DR Congo', order: 35 },
  { name: 'Sentinel', continent: 'africa', country: 'ZM', lat: -12.55, lng: 25.52, resourceType: 'copper', hashrate: 450, price: 120, valuationUsd: '$2.7B', rarity: 'rare', resourceEmoji: '🔴', description: 'Медный рудник, Замбия', descriptionEn: 'Copper mine, Zambia', order: 36 },
  { name: 'Los Bronces', continent: 'south_america', country: 'CL', lat: -33.14, lng: -70.27, resourceType: 'copper', hashrate: 470, price: 125, valuationUsd: '$2.9B', rarity: 'rare', resourceEmoji: '🔴', description: 'Медный рудник, Чили', descriptionEn: 'Copper mine, Chile', order: 37 },
  { name: 'Las Bambas', continent: 'south_america', country: 'PE', lat: -14.06, lng: -72.33, resourceType: 'copper', hashrate: 530, price: 142, valuationUsd: '$3.6B', rarity: 'rare', resourceEmoji: '🔴', description: 'Медный рудник, Перу', descriptionEn: 'Copper mine, Peru', order: 38 },
  { name: 'Udokan', continent: 'russia', country: 'RU', lat: 56.49, lng: 118.37, resourceType: 'copper', hashrate: 420, price: 115, valuationUsd: '$2.5B', rarity: 'rare', resourceEmoji: '🔴', description: 'Медный рудник, Россия', descriptionEn: 'Copper mine, Russia', order: 39 },
  { name: 'Olympic Dam Copper', continent: 'australia', country: 'AU', lat: -30.44, lng: 136.89, resourceType: 'copper', hashrate: 550, price: 148, valuationUsd: '$3.8B', rarity: 'epic', resourceEmoji: '🔴', description: 'Полиметаллический гигант, Австралия', descriptionEn: 'Polymetallic giant, Australia', order: 40 },
  // ===== IRON ORE (20) =====
  { name: 'Carajas Complex', continent: 'south_america', country: 'BR', lat: -6.07, lng: -50.17, resourceType: 'iron', hashrate: 760, price: 205, valuationUsd: '$6.5B', rarity: 'legendary', resourceEmoji: '⚙️', description: 'Крупнейший железорудный район, Бразилия', descriptionEn: 'Largest iron ore district, Brazil', order: 41 },
  { name: 'Hamersley Operations', continent: 'australia', country: 'AU', lat: -22.72, lng: 117.67, resourceType: 'iron', hashrate: 680, price: 180, valuationUsd: '$5B', rarity: 'epic', resourceEmoji: '⚙️', description: 'Железорудный комплекс, Австралия', descriptionEn: 'Iron ore complex, Australia', order: 42 },
  { name: 'Chichester Hub', continent: 'australia', country: 'AU', lat: -22.3, lng: 118.35, resourceType: 'iron', hashrate: 600, price: 160, valuationUsd: '$4.2B', rarity: 'epic', resourceEmoji: '⚙️', description: 'Железорудный хаб, Австралия', descriptionEn: 'Iron ore hub, Australia', order: 43 },
  { name: 'Mount Whaleback', continent: 'australia', country: 'AU', lat: -23.36, lng: 119.68, resourceType: 'iron', hashrate: 580, price: 155, valuationUsd: '$4B', rarity: 'epic', resourceEmoji: '⚙️', description: 'Крупнейший открытый железорудный карьер, Австралия', descriptionEn: 'Largest open-pit iron mine, Australia', order: 44 },
  { name: 'Krivbass', continent: 'europe', country: 'UA', lat: 47.91, lng: 33.39, resourceType: 'iron', hashrate: 500, price: 135, valuationUsd: '$3.3B', rarity: 'rare', resourceEmoji: '⚙️', description: 'Железорудный бассейн, Украина', descriptionEn: 'Iron ore basin, Ukraine', order: 45 },
  { name: 'Kursk Magnetic Anomaly', continent: 'russia', country: 'RU', lat: 51.75, lng: 37.62, resourceType: 'iron', hashrate: 550, price: 148, valuationUsd: '$3.8B', rarity: 'epic', resourceEmoji: '⚙️', description: 'КМА, Россия', descriptionEn: 'KMA, Russia', order: 46 },
  { name: 'Sishen', continent: 'africa', country: 'ZA', lat: -27.73, lng: 22.95, resourceType: 'iron', hashrate: 480, price: 130, valuationUsd: '$3.1B', rarity: 'rare', resourceEmoji: '⚙️', description: 'Железорудный рудник, ЮАР', descriptionEn: 'Iron ore mine, South Africa', order: 47 },
  { name: 'Itabira', continent: 'south_america', country: 'BR', lat: -19.62, lng: -43.23, resourceType: 'iron', hashrate: 520, price: 140, valuationUsd: '$3.5B', rarity: 'rare', resourceEmoji: '⚙️', description: 'Железорудный район, Бразилия', descriptionEn: 'Iron ore district, Brazil', order: 48 },
  { name: 'Anshan', continent: 'asia', country: 'CN', lat: 41.11, lng: 122.99, resourceType: 'iron', hashrate: 540, price: 145, valuationUsd: '$3.6B', rarity: 'rare', resourceEmoji: '⚙️', description: 'Железорудный комплекс, Китай', descriptionEn: 'Iron ore complex, China', order: 49 },
  { name: 'Hope Downs', continent: 'australia', country: 'AU', lat: -22.83, lng: 119.15, resourceType: 'iron', hashrate: 460, price: 125, valuationUsd: '$2.9B', rarity: 'rare', resourceEmoji: '⚙️', description: 'Железорудный рудник, Австралия', descriptionEn: 'Iron ore mine, Australia', order: 50 },
  { name: 'Serrano', continent: 'south_america', country: 'BR', lat: -20.05, lng: -43.87, resourceType: 'iron', hashrate: 440, price: 118, valuationUsd: '$2.6B', rarity: 'rare', resourceEmoji: '⚙️', description: 'Железорудный рудник, Бразилия', descriptionEn: 'Iron ore mine, Brazil', order: 51 },
  { name: 'Solomon Hub', continent: 'australia', country: 'AU', lat: -22.59, lng: 118.5, resourceType: 'iron', hashrate: 470, price: 128, valuationUsd: '$3B', rarity: 'rare', resourceEmoji: '⚙️', description: 'Железорудный хаб, Австралия', descriptionEn: 'Iron ore hub, Australia', order: 52 },
  { name: 'Kiruna', continent: 'europe', country: 'SE', lat: 67.86, lng: 20.22, resourceType: 'iron', hashrate: 530, price: 142, valuationUsd: '$3.5B', rarity: 'epic', resourceEmoji: '⚙️', description: 'Крупнейший подземный железорудный, Швеция', descriptionEn: 'Largest underground iron mine, Sweden', order: 53 },
  { name: 'Mesabi Range', continent: 'north_america', country: 'US', lat: 47.5, lng: -92.5, resourceType: 'iron', hashrate: 450, price: 122, valuationUsd: '$2.8B', rarity: 'rare', resourceEmoji: '⚙️', description: 'Железорудный хребет, США', descriptionEn: 'Iron range, USA', order: 54 },
  { name: 'Sardar', continent: 'asia', country: 'IN', lat: 22.6, lng: 86.15, resourceType: 'iron', hashrate: 420, price: 115, valuationUsd: '$2.5B', rarity: 'rare', resourceEmoji: '⚙️', description: 'Железорудный рудник, Индия', descriptionEn: 'Iron ore mine, India', order: 55 },
  { name: 'Marandoo', continent: 'australia', country: 'AU', lat: -22.67, lng: 118.13, resourceType: 'iron', hashrate: 430, price: 116, valuationUsd: '$2.6B', rarity: 'rare', resourceEmoji: '⚙️', description: 'Железорудный рудник, Австралия', descriptionEn: 'Iron ore mine, Australia', order: 56 },
  { name: 'S11D', continent: 'south_america', country: 'BR', lat: -6.4, lng: -49.66, resourceType: 'iron', hashrate: 700, price: 188, valuationUsd: '$5.5B', rarity: 'epic', resourceEmoji: '⚙️', description: 'Крупнейший железорудный проект, Бразилия', descriptionEn: 'Largest iron ore project, Brazil', order: 57 },
  { name: 'Gundagai', continent: 'australia', country: 'AU', lat: -34.75, lng: 148.1, resourceType: 'iron', hashrate: 380, price: 105, valuationUsd: '$2.2B', rarity: 'common', resourceEmoji: '⚙️', description: 'Железорудный рудник, Австралия', descriptionEn: 'Iron ore mine, Australia', order: 58 },
  { name: 'Zheleznogorsk', continent: 'russia', country: 'RU', lat: 52.33, lng: 35.35, resourceType: 'iron', hashrate: 490, price: 132, valuationUsd: '$3.1B', rarity: 'rare', resourceEmoji: '⚙️', description: 'Железногорск, Россия', descriptionEn: 'Zheleznogorsk, Russia', order: 59 },
  { name: 'Labrador Trough', continent: 'north_america', country: 'CA', lat: 54.8, lng: -66.8, resourceType: 'iron', hashrate: 510, price: 138, valuationUsd: '$3.4B', rarity: 'rare', resourceEmoji: '⚙️', description: 'Железорудный район, Канада', descriptionEn: 'Iron ore district, Canada', order: 60 },
  // ===== RARE METALS (20) =====
  { name: 'Bayan Obo', continent: 'asia', country: 'CN', lat: 41.8, lng: 110.0, resourceType: 'rare_metals', hashrate: 720, price: 195, valuationUsd: '$6B', rarity: 'legendary', resourceEmoji: '⚛️', description: 'Редкоземельный гигант, Китай', descriptionEn: 'Rare earth giant, China', order: 61 },
  { name: 'Salar de Atacama', continent: 'south_america', country: 'CL', lat: -23.5, lng: -68.2, resourceType: 'rare_metals', hashrate: 680, price: 185, valuationUsd: '$5.5B', rarity: 'epic', resourceEmoji: '⚛️', description: 'Литиевый солар, Чили', descriptionEn: 'Lithium salar, Chile', order: 62 },
  { name: 'Greenbushes', continent: 'australia', country: 'AU', lat: -33.85, lng: 116.06, resourceType: 'rare_metals', hashrate: 640, price: 172, valuationUsd: '$4.8B', rarity: 'epic', resourceEmoji: '⚛️', description: 'Литиевый рудник, Австралия', descriptionEn: 'Lithium mine, Australia', order: 63 },
  { name: 'Tenke Fungurume Cobalt', continent: 'africa', country: 'CD', lat: -10.62, lng: 26.14, resourceType: 'rare_metals', hashrate: 600, price: 162, valuationUsd: '$4.3B', rarity: 'epic', resourceEmoji: '⚛️', description: 'Кобальтовый рудник, ДР Конго', descriptionEn: 'Cobalt mine, DR Congo', order: 64 },
  { name: 'Bushveld Complex', continent: 'africa', country: 'ZA', lat: -24.87, lng: 29.44, resourceType: 'rare_metals', hashrate: 650, price: 175, valuationUsd: '$5B', rarity: 'epic', resourceEmoji: '⚛️', description: 'Платина и палладий, ЮАР', descriptionEn: 'Platinum and palladium, South Africa', order: 65 },
  { name: 'Olympic Dam Uranium', continent: 'australia', country: 'AU', lat: -30.43, lng: 136.87, resourceType: 'rare_metals', hashrate: 580, price: 158, valuationUsd: '$4B', rarity: 'epic', resourceEmoji: '⚛️', description: 'Урановый рудник, Австралия', descriptionEn: 'Uranium mine, Australia', order: 66 },
  { name: 'Norilsk', continent: 'russia', country: 'RU', lat: 69.35, lng: 88.2, resourceType: 'rare_metals', hashrate: 700, price: 190, valuationUsd: '$5.8B', rarity: 'legendary', resourceEmoji: '⚛️', description: 'Никель и палладий, Россия', descriptionEn: 'Nickel and palladium, Russia', order: 67 },
  { name: 'Salar de Uyuni', continent: 'south_america', country: 'BO', lat: -20.13, lng: -67.49, resourceType: 'rare_metals', hashrate: 620, price: 168, valuationUsd: '$4.5B', rarity: 'epic', resourceEmoji: '⚛️', description: 'Литиевый солар, Боливия', descriptionEn: 'Lithium salar, Bolivia', order: 68 },
  { name: 'McArthur River', continent: 'north_america', country: 'CA', lat: 57.77, lng: -105.6, resourceType: 'rare_metals', hashrate: 560, price: 152, valuationUsd: '$3.9B', rarity: 'epic', resourceEmoji: '⚛️', description: 'Урановый рудник, Канада', descriptionEn: 'Uranium mine, Canada', order: 69 },
  { name: 'Araxa', continent: 'south_america', country: 'BR', lat: -19.59, lng: -46.94, resourceType: 'rare_metals', hashrate: 540, price: 148, valuationUsd: '$3.7B', rarity: 'rare', resourceEmoji: '⚛️', description: 'Ниобиевый рудник, Бразилия', descriptionEn: 'Niobium mine, Brazil', order: 70 },
  { name: 'Thacker Pass', continent: 'north_america', country: 'US', lat: 41.58, lng: -117.45, resourceType: 'rare_metals', hashrate: 520, price: 142, valuationUsd: '$3.5B', rarity: 'rare', resourceEmoji: '⚛️', description: 'Литиевый проект, США', descriptionEn: 'Lithium project, USA', order: 71 },
  { name: 'Manono', continent: 'africa', country: 'CD', lat: -7.3, lng: 27.42, resourceType: 'rare_metals', hashrate: 500, price: 138, valuationUsd: '$3.3B', rarity: 'rare', resourceEmoji: '⚛️', description: 'Литий и олово, ДР Конго', descriptionEn: 'Lithium and tin, DR Congo', order: 72 },
  { name: 'Inkai', continent: 'asia', country: 'KZ', lat: 44.37, lng: 66.97, resourceType: 'rare_metals', hashrate: 480, price: 132, valuationUsd: '$3.1B', rarity: 'rare', resourceEmoji: '⚛️', description: 'Урановый рудник, Казахстан', descriptionEn: 'Uranium mine, Kazakhstan', order: 73 },
  { name: 'Pitinga', continent: 'south_america', country: 'BR', lat: -0.78, lng: -60.1, resourceType: 'rare_metals', hashrate: 460, price: 125, valuationUsd: '$2.9B', rarity: 'rare', resourceEmoji: '⚛️', description: 'Олово, ниобий, тантал, Бразилия', descriptionEn: 'Tin, niobium, tantalum, Brazil', order: 74 },
  { name: 'Mounana', continent: 'africa', country: 'GA', lat: -1.4, lng: 13.15, resourceType: 'rare_metals', hashrate: 420, price: 115, valuationUsd: '$2.5B', rarity: 'rare', resourceEmoji: '⚛️', description: 'Марганец, уран, Габон', descriptionEn: 'Manganese, uranium, Gabon', order: 75 },
  { name: 'Zhongjia', continent: 'asia', country: 'CN', lat: 25.5, lng: 114.5, resourceType: 'rare_metals', hashrate: 440, price: 120, valuationUsd: '$2.7B', rarity: 'rare', resourceEmoji: '⚛️', description: 'Вольфрам, Китай', descriptionEn: 'Tungsten, China', order: 76 },
  { name: 'Sudbury', continent: 'north_america', country: 'CA', lat: 46.49, lng: -81.0, resourceType: 'rare_metals', hashrate: 550, price: 150, valuationUsd: '$3.8B', rarity: 'epic', resourceEmoji: '⚛️', description: 'Никель, Канада', descriptionEn: 'Nickel, Canada', order: 77 },
  { name: 'Jabal Sayid', continent: 'asia', country: 'SA', lat: 23.79, lng: 40.93, resourceType: 'rare_metals', hashrate: 400, price: 110, valuationUsd: '$2.3B', rarity: 'rare', resourceEmoji: '⚛️', description: 'Редкие металлы, Саудовская Аравия', descriptionEn: 'Rare metals, Saudi Arabia', order: 78 },
  { name: 'Nyang', continent: 'asia', country: 'CN', lat: 36.2, lng: 105.7, resourceType: 'rare_metals', hashrate: 410, price: 112, valuationUsd: '$2.4B', rarity: 'rare', resourceEmoji: '⚛️', description: 'Магний, Китай', descriptionEn: 'Magnesium, China', order: 79 },
  { name: 'Husab', continent: 'africa', country: 'NA', lat: -22.43, lng: 15.02, resourceType: 'rare_metals', hashrate: 530, price: 145, valuationUsd: '$3.6B', rarity: 'rare', resourceEmoji: '⚛️', description: 'Урановый рудник, Намибия', descriptionEn: 'Uranium mine, Namibia', order: 80 },
  // ===== OIL & GAS (15) =====
  { name: 'Ghawar', continent: 'asia', country: 'SA', lat: 25.15, lng: 49.48, resourceType: 'oil_gas', hashrate: 800, price: 250, valuationUsd: '$250B', rarity: 'legendary', resourceEmoji: '🛢️', description: 'Крупнейшее нефтяное месторождение, С.Аравия', descriptionEn: 'Largest oil field, Saudi Arabia', order: 81 },
  { name: 'North Field / South Pars', continent: 'asia', country: 'QA', lat: 26.7, lng: 52.0, resourceType: 'oil_gas', hashrate: 780, price: 240, valuationUsd: '$200B', rarity: 'legendary', resourceEmoji: '🛢️', description: 'Крупнейшее газовое месторождение, Катар/Иран', descriptionEn: 'Largest gas field, Qatar/Iran', order: 82 },
  { name: 'Permian Basin', continent: 'north_america', country: 'US', lat: 31.95, lng: -102.15, resourceType: 'oil_gas', hashrate: 750, price: 225, valuationUsd: '$180B', rarity: 'legendary', resourceEmoji: '🛢️', description: 'Нефтеносный бассейн, США', descriptionEn: 'Oil basin, USA', order: 83 },
  { name: 'Urengoy', continent: 'russia', country: 'RU', lat: 65.97, lng: 78.37, resourceType: 'oil_gas', hashrate: 700, price: 200, valuationUsd: '$120B', rarity: 'legendary', resourceEmoji: '🛢️', description: 'Газовое месторождение, Россия', descriptionEn: 'Gas field, Russia', order: 84 },
  { name: 'Athabasca Oil Sands', continent: 'north_america', country: 'CA', lat: 57.0, lng: -111.5, resourceType: 'oil_gas', hashrate: 680, price: 190, valuationUsd: '$100B', rarity: 'epic', resourceEmoji: '🛢️', description: 'Нефтяные пески, Канада', descriptionEn: 'Oil sands, Canada', order: 85 },
  { name: 'Samotlor', continent: 'russia', country: 'RU', lat: 61.18, lng: 76.73, resourceType: 'oil_gas', hashrate: 620, price: 170, valuationUsd: '$80B', rarity: 'epic', resourceEmoji: '🛢️', description: 'Нефтяное месторождение, Россия', descriptionEn: 'Oil field, Russia', order: 86 },
  { name: 'Tengiz', continent: 'asia', country: 'KZ', lat: 46.15, lng: 53.35, resourceType: 'oil_gas', hashrate: 640, price: 175, valuationUsd: '$90B', rarity: 'epic', resourceEmoji: '🛢️', description: 'Нефтяное месторождение, Казахстан', descriptionEn: 'Oil field, Kazakhstan', order: 87 },
  { name: 'Kashagan', continent: 'asia', country: 'KZ', lat: 46.45, lng: 51.87, resourceType: 'oil_gas', hashrate: 660, price: 182, valuationUsd: '$95B', rarity: 'epic', resourceEmoji: '🛢️', description: 'Нефтяное месторождение, Казахстан', descriptionEn: 'Oil field, Kazakhstan', order: 88 },
  { name: 'Prudhoe Bay', continent: 'north_america', country: 'US', lat: 70.25, lng: -148.33, resourceType: 'oil_gas', hashrate: 580, price: 158, valuationUsd: '$70B', rarity: 'epic', resourceEmoji: '🛢️', description: 'Нефтяное месторождение, Аляска', descriptionEn: 'Oil field, Alaska, USA', order: 89 },
  { name: 'Hassi Messaoud', continent: 'africa', country: 'DZ', lat: 31.68, lng: 6.07, resourceType: 'oil_gas', hashrate: 550, price: 150, valuationUsd: '$60B', rarity: 'epic', resourceEmoji: '🛢️', description: 'Нефтяное месторождение, Алжир', descriptionEn: 'Oil field, Algeria', order: 90 },
  { name: 'Hassi R Mel', continent: 'africa', country: 'DZ', lat: 33.26, lng: 3.29, resourceType: 'oil_gas', hashrate: 540, price: 148, valuationUsd: '$55B', rarity: 'epic', resourceEmoji: '🛢️', description: 'Газовое месторождение, Алжир', descriptionEn: 'Gas field, Algeria', order: 91 },
  { name: 'Zapolyarnoye', continent: 'russia', country: 'RU', lat: 67.6, lng: 78.6, resourceType: 'oil_gas', hashrate: 560, price: 155, valuationUsd: '$65B', rarity: 'epic', resourceEmoji: '🛢️', description: 'Газовое месторождение, Россия', descriptionEn: 'Gas field, Russia', order: 92 },
  { name: 'Daqing', continent: 'asia', country: 'CN', lat: 46.59, lng: 124.98, resourceType: 'oil_gas', hashrate: 520, price: 142, valuationUsd: '$50B', rarity: 'rare', resourceEmoji: '🛢️', description: 'Нефтяное месторождение, Китай', descriptionEn: 'Oil field, China', order: 93 },
  { name: 'Bakken Formation', continent: 'north_america', country: 'US', lat: 48.2, lng: -103.6, resourceType: 'oil_gas', hashrate: 500, price: 138, valuationUsd: '$45B', rarity: 'rare', resourceEmoji: '🛢️', description: 'Нефтяная формация, США', descriptionEn: 'Oil formation, USA', order: 94 },
  { name: 'Hibernia', continent: 'north_america', country: 'CA', lat: 46.75, lng: -48.78, resourceType: 'oil_gas', hashrate: 480, price: 132, valuationUsd: '$40B', rarity: 'rare', resourceEmoji: '🛢️', description: 'Морское нефтяное месторождение, Канада', descriptionEn: 'Offshore oil field, Canada', order: 95 },
  // ===== DIAMONDS (10) =====
  { name: 'Jwaneng', continent: 'africa', country: 'BW', lat: -24.52, lng: 24.73, resourceType: 'diamonds', hashrate: 700, price: 195, valuationUsd: '$6B', rarity: 'legendary', resourceEmoji: '💎', description: 'Самый богатый алмазный рудник, Ботсвана', descriptionEn: 'Richest diamond mine, Botswana', order: 96 },
  { name: 'Orapa', continent: 'africa', country: 'BW', lat: -21.29, lng: 25.38, resourceType: 'diamonds', hashrate: 600, price: 165, valuationUsd: '$4.5B', rarity: 'epic', resourceEmoji: '💎', description: 'Алмазный рудник, Ботсвана', descriptionEn: 'Diamond mine, Botswana', order: 97 },
  { name: 'Catoca', continent: 'africa', country: 'AO', lat: -9.45, lng: 20.33, resourceType: 'diamonds', hashrate: 560, price: 155, valuationUsd: '$4B', rarity: 'epic', resourceEmoji: '💎', description: 'Алмазный рудник, Ангола', descriptionEn: 'Diamond mine, Angola', order: 98 },
  { name: 'Udachny', continent: 'russia', country: 'RU', lat: 66.43, lng: 112.35, resourceType: 'diamonds', hashrate: 580, price: 160, valuationUsd: '$4.2B', rarity: 'epic', resourceEmoji: '💎', description: 'Алмазный рудник, Россия', descriptionEn: 'Diamond mine, Russia', order: 99 },
  { name: 'Lomonosov', continent: 'russia', country: 'RU', lat: 65.4, lng: 40.9, resourceType: 'diamonds', hashrate: 520, price: 142, valuationUsd: '$3.5B', rarity: 'rare', resourceEmoji: '💎', description: 'Алмазный рудник, Россия', descriptionEn: 'Diamond mine, Russia', order: 100 },
  { name: 'Argyle', continent: 'australia', country: 'AU', lat: -16.71, lng: 128.39, resourceType: 'diamonds', hashrate: 480, price: 130, valuationUsd: '$3B', rarity: 'rare', resourceEmoji: '💎', description: 'Алмазный рудник, Австралия', descriptionEn: 'Diamond mine, Australia', order: 101 },
  { name: 'Ekati', continent: 'north_america', country: 'CA', lat: 64.72, lng: -110.62, resourceType: 'diamonds', hashrate: 500, price: 138, valuationUsd: '$3.3B', rarity: 'rare', resourceEmoji: '💎', description: 'Алмазный рудник, Канада', descriptionEn: 'Diamond mine, Canada', order: 102 },
  { name: 'Diavik', continent: 'north_america', country: 'CA', lat: 64.5, lng: -110.27, resourceType: 'diamonds', hashrate: 490, price: 135, valuationUsd: '$3.2B', rarity: 'rare', resourceEmoji: '💎', description: 'Алмазный рудник, Канада', descriptionEn: 'Diamond mine, Canada', order: 103 },
  { name: 'Venetia', continent: 'africa', country: 'ZA', lat: -22.43, lng: 29.32, resourceType: 'diamonds', hashrate: 540, price: 148, valuationUsd: '$3.6B', rarity: 'rare', resourceEmoji: '💎', description: 'Алмазный рудник, ЮАР', descriptionEn: 'Diamond mine, South Africa', order: 104 },
  { name: 'Letseng', continent: 'africa', country: 'LS', lat: -29.0, lng: 28.9, resourceType: 'diamonds', hashrate: 460, price: 125, valuationUsd: '$2.8B', rarity: 'rare', resourceEmoji: '💎', description: 'Алмазный рудник, Лесото', descriptionEn: 'Diamond mine, Lesotho', order: 105 },
  // ===== COAL (5) =====
  { name: 'Shenfu', continent: 'asia', country: 'CN', lat: 39.6, lng: 110.3, resourceType: 'coal', hashrate: 550, price: 150, valuationUsd: '$3.8B', rarity: 'epic', resourceEmoji: '⚫', description: 'Угольный бассейн, Китай', descriptionEn: 'Coal basin, China', order: 106 },
  { name: 'Ekibastuz', continent: 'asia', country: 'KZ', lat: 51.73, lng: 75.32, resourceType: 'coal', hashrate: 500, price: 138, valuationUsd: '$3.2B', rarity: 'rare', resourceEmoji: '⚫', description: 'Угольный разрез, Казахстан', descriptionEn: 'Coal mine, Kazakhstan', order: 107 },
  { name: 'Cerrejon', continent: 'south_america', country: 'CO', lat: 11.09, lng: -72.66, resourceType: 'coal', hashrate: 480, price: 132, valuationUsd: '$3B', rarity: 'rare', resourceEmoji: '⚫', description: 'Угольный рудник, Колумбия', descriptionEn: 'Coal mine, Colombia', order: 108 },
  { name: 'Jamshedpur', continent: 'asia', country: 'IN', lat: 22.8, lng: 86.2, resourceType: 'coal', hashrate: 460, price: 125, valuationUsd: '$2.8B', rarity: 'rare', resourceEmoji: '⚫', description: 'Угольный район, Индия', descriptionEn: 'Coal district, India', order: 109 },
  { name: 'Donbas', continent: 'europe', country: 'UA', lat: 48.02, lng: 37.8, resourceType: 'coal', hashrate: 440, price: 118, valuationUsd: '$2.5B', rarity: 'rare', resourceEmoji: '⚫', description: 'Угольный бассейн, Украина', descriptionEn: 'Coal basin, Ukraine', order: 110 },
];

async function seedMiningSites() {
  try {
    await mongoose.connect(process.env.MONGO_URI || 'mongodb://localhost:27017/dgtl_miniapp');
    console.log('Connected to MongoDB');
    await Icon.deleteMany({});

    const sites = MINING_SITES.map(site => ({
      ...site,
      nameEn: site.name,
      price: site.price * 1000000,
      imageUrl: RESOURCE_ICONS[site.resourceType] || '/icons/resources/gold.svg',
      shareLabel: '1/10 доли',
      shareLabelEn: '1/10 share',
      totalShares: 10,
      availableShares: 10,
      isActive: true,
      starsPrice: Math.max(1, Math.round(site.price / 2)),
      stakingRate: site.hashrate,
    }));

    await Icon.insertMany(sites);
    console.log(`Seeded ${sites.length} sites.`);
    mongoose.disconnect();
  } catch (err) {
    console.error('Seed error:', err);
    process.exit(1);
  }
}
seedMiningSites();
